---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
data:
  HOST: postgres
  PORT: "5432"
  USER: root
  PASSWORD: gladiators88