---
apiVersion: v1
kind: Service
metadata:    
  name: odoo
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "odoo.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069